### ISSUE TITLE
Setting: 환경 설정

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#1]
# TODO
- [x] 프로젝트 생성
- [x] ERD -> Entity 로 변경
- [x] 공통 예외 처리
- [x] 시큐리티 설정
- [x] 테스트 설정
- [x] 도커 자동 배포 설정

**Comment by sieunnnn** [comment]
# TODO
- [ ] 문자인증 dependency 추가
