### ISSUE TITLE
Feat: 유저 기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#3]

**Comment by sieunnnn** [comment]
# TODO
- [ ] 문자인증 dependency 추가 후 브랜치 최신화
- [ ] 회원가입 로그인 와이어 프레임 보면서
  - [ ] 필요한 클래스 작성
  - [ ] 불필요한 / 필요한 엔티티 필드 추가

**Comment by codesooo** [comment]
# TODO

- [ ] 회원가입
   - [x] 랜덤 넘버 생성과 처리
   - [x] 랜덤 닉네임 생성과 처리
     - [ ] 회원 가입 시에는 랜덤 닉네임으로 자동 생성되게 변경 (이후 마이페이지에서 수정 가능)
   - [ ] 문자 인증 구현

- [ ]  기본 로그인
   - [x] 로직 구현

- [ ] 소셜 로그인
   - [x] 기본 틀 구현
   - [ ]  로직 구현
   
- [x] 로그아웃
- [x] 토큰 갱신
- [x] 유저 관련 엔티티 생성

**Comment by codesooo** [comment]
유저 테이블에 name, phoneNumber 추가됨
- [ ] 관련 코드 수정
