### ISSUE TITLE
Data: TourAPI 데이터 처리 기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#4]
# TODO
- [ ] 엔티티 생성 / 매핑
- [ ] 데이터 자동으로 받아오고 갱신하는 기능 구현
- [ ] 스케줄러 생성
- [ ] 캐싱
  - 이미 정해져 있는 투어 정보의 경우 수정될 일이 없고, READ 만 할 거기 때문에 캐싱 기능이 좋아보인다.
  - 대신 리뷰는 갱신되기 때문에 이는 쿼리를 던져야 할 것 같다.

**Comment by sieunnnn** [comment]
# 24. 06. 11
Review 기능 제외 엔티티 생성 / 매핑 완료 하였습니다.

**Comment by sieunnnn** [comment]
# 24. 06. 12
## 데이터 처리
### Tour API
#### 공통
- [ ] 콘텐츠 타입 csv 입력
- [ ] 대분류 / 중분류 / 소분류 입력
#### 스팟 데이터
- [ ] detailCommon1 / /detailIntro1 / detailInfo1 / detailImage1 받아서 저장하기
#### 도보코스
- [ ] 스팟 데이터와 같이 데이터 받아서 저장하기
### 올레코스
- [ ] .gpx -> csv 변환
- [ ] 분류 데이터 저장하기
- [ ] 세부 데이터 저장하기

## 데이터 -> 데이터 베이스
- [ ] 컨트롤러 기능 구현
  - csv 파일을 자동으로 db 에 저장할 수 있도록 하기 위함입니다.
- [ ] 데이터 캐싱 기능 구현
  - 똑같은 내용을 반복해서 보여주기 때문에 json 형태로 캐싱 해두는 것이 좋아 보입니다.
  - [ ] 위 기능을 달에 한번씩 수행하는 스케줄러 기능 구현
    - 데이터가 갱신될 가능성이 존재하기 때문에 해당 기능을 구현하였습니다.
