### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by codesooo** [JejuGudGo/Backend#5]
- [ ] 회원가입
   - [x] 랜덤 넘버 생성과 처리
   - [x] 랜덤 닉네임 생성과 처리
     - [ ] 회원 가입 시에는 랜덤 닉네임으로 자동 생성되게 변경 (이후 마이페이지에서 수정 가능)
   - [ ] 문자 인증 구현

- [ ]  기본 로그인
   - [x] 로직 구현

- [ ] 소셜 로그인
   - [x] 기본 틀 구현
   - [ ]  로직 구현
   
- [x] 로그아웃
- [x] 토큰 갱신
- [x] 유저 관련 엔티티 생성
