### ISSUE TITLE
Data/Validation: 산책로, 행사 데이터 처리와 관련 기능 점검하기

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#74]
# TODO
## 데이터 구조 점검
- [x] 산책로, 행사 데이터 구조 확인
- [x] ERD 생성

<br>

## 데이터 구축
- [x] 산책로 csv -> DB 저장
- [x] 행사 csv -> DB 저장

<br>

### 산책로
- [x] 산책로 리스트 반환
  - 태그별 산책로 리스트 반환
- [x] 산책로 상세 데이터 반환
### 행사
- [x] 행사 리스트 반환
  - 상태별 행사 리스트 반환

**Comment by sieunnnn** [comment]
# TODO
- [ ] 산책로 api 분리
- [ ] 행사 데이터, 산책로 데이터 통일되는지 점검하기
