### ISSUE TITLE
Data/Validate: Tour api 데이터 점검

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#81]
# TODO
## ERD 점검
- [x] 필요없는 entity 제거
- [x] 카테고리 Enum 화

## 데이터 추가 자동화
- [x] commandLiner 를 위한 테이블 추가
  - 현재 데이터를 어디까지 받아왔는지 확인하기 위함
- [ ] **[후순위]** `배포` 시 사용할 스케줄러 생성

**Comment by sieunnnn** [comment]
# 편의점 데이터 추가 
- https://safemap.go.kr/main/smap.do 에서 open api 를 활용하여 데이터를 추가하였습니다.
- 시군구 필터링이 되지 않아서, 전체 데이터 중 주소에 제주가 있는 경우를 필터링 -> 점검/수정하여 추가하였습니다.
- 실제 편의점 개수와 맞는지 파악이 어려워 이점은 추후 문구를 넣어야 할 수 도 있을 것 같습니다.
