### ISSUE TITLE
Rafac: olle data 추가

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#94]
# TODO
- [x] erd 수정
- [x] csv 수정, gpx 수급
- [x] 올레타입 반환필드에 반영
- [x] 설명 데이터 있는지 점검 -> 있으면 반영
- [x] 관련 api 생성
  - 올레 리스트 반환
  - 올레 상세 반환
- [x] 명세 작성

**Comment by sieunnnn** [comment]
으악 이거 제가 했는데 말씀 드릴걸 그랫네요 ㅠㅠ
