### ISSUE TITLE
Feat: 코스 검색기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [JejuGudGo/Backend#97]
# TODO
## 공통
- [x] ERD 수정
- [x] 태그 생성
  - 제주걷고 태그 중분류
  - 리뷰 태그 생성
- [x] 공통 response dto 생성

## 텍스트 기반 검색
- [x] kafka, elastic search setting (docker / spring boot)
- [x] kafka 공통 publisher 생성
- [x] elastic document / repository
  - JejuGudgoCourse / spot
  - OlleCourse / spot
  - Trail
- [x] elastic data 동기화를 위한 메서드 생성
  - 전체 데이터 동기화 (최초한번을 위한)
- [ ] redis caching
  - text search result index list
  - '전체' 에 해당하는 데이터 캐싱 메서드
    - 누군가가 전체를 누르면 **비동기적으로 갱신**
    -> 조금 더 고민해보기 (경우의 수 고려)

## 태그 기반 검색
- [x] 위치 계산 메서드
- [x] 위치 기반 > 태그 기반 으로 가도록 구현
- [x] 동적 쿼리 생성

**Comment by sieunnnn** [comment]
# TODO
## 공통
- [ ] 카테고리가 맞지 않을 때, 빈 배열 반환하도록 수정 
- [ ] 제주객의 길을 원작자가 삭제했을 경우, 검색결과에 나오지 않도록 처리
- [ ] 태그 이름 같도록 변경
## 태그 검색
- [ ] 해당 태그가 존재하지 않을 때, 오류를 반환 하는 것이 아닌 빈 배열 반환하도록 처리

**Comment by sieunnnn** [comment]
# TODO
- [ ] 산책로 리뷰 생성 후 제대로 반환되는지 테스트
  - 유저 생성 테스트 코드 작성
  - 리뷰 생성 테스트 코드 작성
- [ ] 명세 작성
