### ISSUE TITLE
Feat : 코스 생성 기능 구현

### ISSUE THREAD

**Issue by codesooo** [JejuGudGo/Backend#98]
# TODO

## 코스 생성
- [x] 코스 생성
  - [x] UserJejuGudgo에 생성됨
  - [x] summary : "시작점-도착점"

## 코스 수정
원작자가 코스를 수정할 시, 해당 코스를 조회하는 모든 곳에서 동일하게 수정되어야 한다.
- [x] 원작자 유저가 코스 이름/설명/대표이미지을 수정함
   - [x] JejuGudgoCourse에서 `title/content/imageUrl`이 수정됨
   - [x] UserJejuGudgoCourse에서, 해당 JejuGudgoCourse와 매핑되어 있는 모든 인스턴스들의 `title/content/imageUrl`이 동일하게 수정

## 코스 삭제
원작자가 코스를 삭제할 시, 제주객의 길 목록에서는 조회 불가능하다. 단, 해당 코스를 완주한 유저들의 마이걷고에서는 조회 가능하다. 이때, 클릭할 시 상세 조회는 불가능하다.

## 코스 걷기
- [x] 원작자의 코스 최초 1회 걷기
   - [x] 원작자가 선택한 걷기 옵션이 저장됨
   - [x] 모든 스팟 완료 시 UserJejuGudgo 완료 처리
   - [x] JejuGudgoCourse, JejuGudgoCourseSpot에 생성됨

- [x] 다른 유저의 코스 걷기
   - [x] db에 저장된 걷기 옵션 노출 필요 (get)
   - [x] 모든 스팟 완료 시 UserJejuGudgo 완료 처리

**Comment by codesooo** [comment]
# 24.11.21

##  📢ERD 수정
- 원본 코스가 삭제될 시에, 마이걷고에서 목록 조회는 가능하나 상세조회는 불가능합니다. 따라서, 프론트에게 해당 코스 삭제여부를 함께 반환해주기 위해 `JejuGudgoCourse` 테이블에 `isDeleted` 컬럼을 추가하였습니다.

![image](https://github.com/user-attachments/assets/e8b7d987-2547-4ab1-988f-c6466587d5a6)

**Comment by codesooo** [comment]
# ERD 수정

## JejuGudgoCourse 
`JejuGudgoCourse` 엔티티에 `isDeleted` 필드를 추가하였습니다. 원작자가 코스를 삭제할 시, 제주객의 길 목록에서는 조회 불가능하나, 해당 코스를 완주한 유저들의 마이걷고에서는 조회 가능합니다. 따라서, 이를 관리하기 위해 해당 필드를 추가하였습니다.
![image](https://github.com/user-attachments/assets/ba77b4bf-a2ab-48d2-ac54-f93548f29d75)

## JejuGudgoCourseOption
`JejuGudgoCourseOption` 엔티티를 생성하였습니다. 코스를 생성하고 최초 1회 걷기를 수행할 때 선택되는 걷기 옵션을 저장하기 위함입니다.
![image](https://github.com/user-attachments/assets/abc58ace-5266-4848-b1b2-e76b2cfca386)

**Comment by codesooo** [comment]
# 24.12.13
- 코스 생성, 수정, 삭제 기능 구현 완료하였습니다.
- 코스를 생성하면 4가지 도보 경로 옵션에 대해 도보 경로 데이터가 저장됩니다.
